### PR TITLE
formatting, PromieSocket logging

### PR DESCRIPTION
**Pull request by kovapatrik**
I've tested the socket now, it's working like a charm - and the communication is really fast, so thanks for the fix! I couldn't wrap my head aroung Node.js TCP solution...

Also I've noticed we have differenct coding styles so I've added prettier to the project. I don't insist on any of the rules, they are mostly the defaults, but this will keep the code nicer and cleaner. Also there is a pre-commit hook which will format the code.

### CODE REVIEW

**Comment by kovapatrik** [comment]
If everything checks for you too, I think after merging this PR to your branch we can merge your PR and create a release. Also I don't know what v1.0 will mean (maybe if all accessories, which can be found in the Python version, are implemented? I don't know if that's a valid goal)

**Comment by dkerr64** [comment]
> I've tested the socket now, it's working like a charm - and the communication is really fast, so thanks for the fix! I couldn't wrap my head aroung Node.js TCP solution...
> 
> Also I've noticed we have differenct coding styles so I've added prettier to the project. I don't insist on any of the rules, they are mostly the defaults, but this will keep the code nicer and cleaner. Also there is a pre-commit hook which will format the code.

I use Visual Studio Code and a TypeScript formatter in that, a quick hotkey and it makes a whole file pretty.  I don't know how different that is from your style.

**Comment by dkerr64** [comment]
This can't be automatically merged so it will take some time to merge this is piece by piece.  We probably both touched the same file(s)

**Comment by kovapatrik** [comment]
> > I've tested the socket now, it's working like a charm - and the communication is really fast, so thanks for the fix! I couldn't wrap my head aroung Node.js TCP solution...
> > Also I've noticed we have differenct coding styles so I've added prettier to the project. I don't insist on any of the rules, they are mostly the defaults, but this will keep the code nicer and cleaner. Also there is a pre-commit hook which will format the code.
> 
> I use Visual Studio Code and a TypeScript formatter in that, a quick hotkey and it makes a whole file pretty. I don't know how different that is from your style.

Same, but those formatters won't break line when it's too long, etc... In the end it doesn't hurt that the style is consistent.

**Comment by dkerr64** [comment]
> If everything checks for you too, I think after merging this PR to your branch we can merge your PR and create a release. Also I don't know what v1.0 will mean (maybe if all accessories, which can be found in the Python version, are implemented? I don't know if that's a valid goal)

I think it is rather ambitious to support everything that the python version does.  I only have a dehumidifier, you (I presume) only have an air conditioner.  They best we can do is provide a framework and some documentation and encourage others to add additional devices.

**Pull request merged**
